[package]
name = "the-key"
description = "A simple fast key management tool for key-value stores"
version = "0.0.5-beta.3"
authors = ["Artur Aralin <artur.aralin97@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ArturAralin/rust-the-key"
license = "MIT"
